export const spanishGlosses300: Readonly<Record<string, string>> = {
  "era": "was",
  "eran": "were",
  "erizaban": "bristled",
  "es": "is",
  "esa": "that",
  "esas": "those",
  "escalofrío": "chill",
  "escondida": "hidden",
  "ese": "that",
  "eso": "that",
  "espanto": "terror",
  "españa": "Spain",
  "especial": "special",
  "ésta": "this one",
  "estaba": "was",
  "estar": "to be",
  "estatuas": "statues",
  "estatura": "stature",
  "este": "this one",
  "éste": "this one",
  "esto": "this",
  "estos": "these",
  "estremecimiento": "shudder",
  "estremecimientos": "shudders",
  "estuco": "stucco",
  "estupefacta": "stunned",
  "estupor": "stupor",
  "estuviera": "were",
  "estuvo": "was",
  "eternos": "eternal",
  "examinó": "examined",
  "exigió": "demanded",
  "existe": "exists",
  "expansiva": "expansive",
  "explico": "explain",
  "explicó": "explained",
  "explosión": "explosion",
  "extinguiéndose": "fading",
  "extrañada": "surprised",
  "extraño": "strange",
  "extraordinariamente": "extraordinarily",
  "extravío": "misplaced",
  "extremo": "extreme",
  "faltaba": "was missing",
  "fama": "fame",
  "favorable": "favorable",
  "femenino": "feminine",
  "fiado": "on credit",
  "fijamente": "intently",
  "fijos": "fixed",
  "fin": "end",
  "finales": "finals",
  "firmado": "signed",
  "físicos": "physical",
  "flandes": "Flanders",
  "flechó": "shot an arrow",
  "flores": "flowers",
  "flotantes": "floating",
  "fondo": "background",
  "forma": "form",
  "fortuna": "fortune",
  "forzado": "forced",
  "fósforos": "matches",
  "francisco": "Francisco",
  "frío": "cold",
  "frisos": "friezes",
  "fruela": "strawberry",
  "fue": "was",
  "fuera": "outside",
  "fueron": "were",
  "funda": "case",
  "fúnebremente": "mournfully",
  "furtiva": "stealthy",
  "galán": "gallant",
  "galanes": "gallants",
  "gastaba": "spent",
  "general": "general",
  "gimoteó": "whimpered",
  "glacial": "glacial",
  "gracia": "grace",
  "gran": "great",
  "gritaba": "shouted",
  "gritar": "shout",
  "grito": "shout",
  "gusto": "taste",
  "había": "there was",
  "habían": "there were",
  "habitual": "habitual",
  "habla": "speaks",
  "hablaba": "spoke",
  "habría": "would have",
  "habríame": "would have had",
  "hacen": "do",
  "hacer": "to do",
  "hacía": "was doing",
  "hacían": "were doing",
  "hallaban": "found",
  "hallarlos": "to find them",
  "hasta": "until",
  "hay": "there is",
  "hayan": "there are",
  "heló": "froze",
  "heredar": "inherit",
  "herencia": "inheritance",
  "hicieron": "they did",
  "hija": "daughter",
  "hijo": "son",
  "hijos": "children",
  "hinchado": "swollen",
  "historia": "story",
  "hombre": "man",
  "hombros": "shoulders",
  "honda": "deep",
  "honorato": "honorable",
  "hora": "hour",
  "horas": "hours",
  "horror": "horror",
  "hostia": "host",
  "hostil": "hostile",
  "hoy": "today",
  "hubiera": "would have",
  "hubo": "there was",
  "hueco": "hollow",
  "humana": "human",
  "hundimiento": "sinking",
  "iba": "was going",
  "ildefonso": "Ildefonso",
  "impasible": "impassive",
  "impedido": "disabled",
  "imperceptible": "imperceptible",
  "impresión": "impression",
  "incansable": "tireless",
  "incauta": "unwary",
  "indiferente": "indifferent",
  "inerte": "inert",
  "inexplicable": "inexplicable",
  "influenza": "influenza",
  "influía": "influenced",
  "inmóvil": "motionless",
  "insidiosamente": "insidiously",
  "intervino": "intervened",
  "inútilmente": "in vain",
  "inventado": "invented",
  "jardín": "garden",
  "jordán": "Jordan",
  "joven": "young",
  "jugaba": "was playing",
  "juntos": "together",
  "juramento": "oath",
  "jurar": "to swear",
};
