export const spanishGlosses0: Readonly<Record<string, string>> = {
  "a": "a",
  "abandono": "abandonment",
  "abandonó": "abandoned",
  "abierta": "open",
  "abiertos": "open",
  "abril": "April",
  "abrió": "opened",
  "absolutamente": "absolutely",
  "absolutos": "absolute",
  "acababa": "was finishing",
  "acariciándola": "caressing her",
  "acaudalado": "wealthy",
  "aceptó": "accepted",
  "acercó": "approached",
  "adelgazara": "had lost weight",
  "adornaban": "adorned",
  "adquirir": "acquire",
  "afirmaba": "asserted",
  "agitado": "agitated",
  "agónico": "agonizing",
  "agravado": "aggravated",
  "agudísima": "extremely sharp",
  "ahogaba": "choking",
  "ahogado": "choked",
  "ajuar": "trousseau",
  "ajustaba": "adjusted",
  "al": "to",
  "alarido": "scream",
  "alarmose": "became alarmed",
  "alcanzando": "reaching",
  "alcanzó": "reached",
  "alcázar": "fortress",
  "alegando": "claiming",
  "alfombra": "carpet",
  "algunos": "some",
  "alicia": "Alicia",
  "allí": "there",
  "alma": "soul",
  "almohadón": "pillow",
  "almohadones": "pillows",
  "alta": "tall",
  "altas": "tall",
  "altivo": "haughty",
  "alucinaciones": "hallucinations",
  "amaba": "loved",
  "amanecía": "dawned",
  "amaneció": "dawned",
  "amantes": "lovers",
  "ambos": "both",
  "amenazó": "threatened",
  "américa": "America",
  "amigos": "friends",
  "amor": "love",
  "amores": "loves",
  "anda": "go",
  "anemia": "anemia",
  "angelical": "angelic",
  "animal": "animal",
  "anticipaba": "anticipated",
  "antiguos": "ancient",
  "antonio": "Antonio",
  "antropoide": "anthropoid",
  "años": "years",
  "aparecer": "appear",
  "apenas": "barely",
  "aplicado": "applied",
  "apoyada": "supported",
  "apoyado": "supported",
  "aquella": "that one",
  "aquí": "here",
  "aragonés": "Aragonese",
  "aritmética": "arithmetic",
  "armas": "weapons",
  "arrancó": "set off",
  "arrastraban": "dragged",
  "arrastró": "dragged",
  "arreglaran": "arranged",
  "arrogante": "arrogant",
  "arsenal": "arsenal",
  "articuló": "articulated",
  "artículo": "article",
  "así": "like that",
  "ataque": "attack",
  "atención": "attention",
  "aun": "even",
  "aún": "still",
  "aunque": "although",
  "avanzaba": "was advancing",
  "avanzaron": "advanced",
  "aves": "birds",
  "baja": "low",
  "bandós": "flocks",
  "belleza": "beauty",
  "bermejo": "reddish",
  "blancura": "whiteness",
  "boca": "mouth",
  "bola": "ball",
  "borrascoso": "stormy",
  "botica": "apothecary",
  "brazo": "arm",
  "brazos": "arms",
  "brillantes": "shiny",
  "brillo": "shine",
  "bruscamente": "abruptly",
  "buscar": "search",
  "caballero": "gentleman",
  "cabellos": "hair",
  "cabeza": "head",
  "cada": "each",
  "cadeneta": "chain",
  "caer": "fall",
  "caído": "fallen",
  "cajón": "drawer",
  "callado": "quiet",
  "callao": "Callao",
  "calle": "street",
  "calma": "calm",
  "cama": "bed",
  "caminaba": "was walking",
  "camisa": "shirt",
  "carácter": "character",
  "cargados": "loaded",
  "caricia": "caress",
  "carnes": "meat",
  "caro": "expensive",
  "casa": "house",
  "casado": "married",
  "casados": "married",
  "casarla": "to marry her",
  "casase": "to marry",
  "casi": "almost",
  "caso": "case",
  "cautivan": "captivate",
  "cayó": "fell",
  "cesar": "cease",
  "chisme": "gossip",
  "chupándole": "sucking on",
  "cid": "Cid",
  "cielo": "sky",
  "ciertas": "certain",
  "cinco": "five",
  "clamó": "cried out",
  "colcha": "bedspread",
  "colector": "drain",
  "colores": "colors",
  "columnas": "columns",
  "comedor": "dining room",
  "comenzó": "began",
  "como": "as",
  "cómo": "how",
};
