export const spanishGlosses150: Readonly<Record<string, string>> = {
  "completamente": "completely",
  "con": "with",
  "concierto": "agreement",
  "concluido": "concluded",
  "condición": "condition",
  "condiciones": "conditions",
  "confesando": "confessing",
  "confianza": "trust",
  "confrontación": "confrontation",
  "confusas": "confusing",
  "conocer": "to know",
  "conocimiento": "knowledge",
  "conoció": "knew",
  "consintiera": "would consent",
  "consintió": "consented",
  "constatose": "was confirmed",
  "consulta": "consultation",
  "contenía": "contained",
  "contestó": "answered",
  "continuaban": "continued",
  "convengamos": "let’s agree",
  "corazón": "heart",
  "cordoncillo": "cord",
  "corona": "crown",
  "coronada": "crowned",
  "corrió": "ran",
  "cortésmente": "courteously",
  "cortó": "cut",
  "cosa": "thing",
  "costaron": "cost",
  "creer": "believe",
  "creo": "I believe",
  "crepusculares": "twilight",
  "creyó": "believed",
  "crispadas": "tense",
  "cristiano": "Christian",
  "cruzar": "cross",
  "cuando": "when",
  "cuello": "neck",
  "culpa": "blame",
  "cumplió": "fulfilled",
  "curanderas": "healers",
  "curiosidad": "curiosity",
  "cuya": "whose",
  "d": "d",
  "damisela": "damsel",
  "dar": "to give",
  "darlo": "to give it",
  "de": "of",
  "debía": "should",
  "debilidad": "weakness",
  "decir": "to say",
  "decirlo": "to say it",
  "declararon": "they declared",
  "dedos": "fingers",
  "dejado": "left",
  "dejar": "to leave",
  "dejaría": "would leave",
  "dejó": "left",
  "del": "of",
  "delante": "in front of",
  "delirio": "delirium",
  "deliró": "raved",
  "demás": "besides",
  "dentro": "inside",
  "desalentado": "discouraged",
  "desangrándose": "bleeding out",
  "desapacible": "unpleasant",
  "desarrollo": "development",
  "descanso": "rest",
  "descendieron": "descended",
  "desde": "from",
  "deseado": "desired",
  "desenredar": "untangle",
  "deshacer": "undo",
  "desmayos": "fainting spells",
  "desmejoraba": "was deteriorating",
  "desmesuradamente": "excessively",
  "despertar": "awaken",
  "despidió": "said goodbye",
  "despierta": "awake",
  "desplomada": "collapsed",
  "después": "after",
  "desvanecida": "faded",
  "día": "day",
  "diablo": "devil",
  "diálogo": "dialogue",
  "diaria": "daily",
  "días": "days",
  "dicha": "joy",
  "dicho": "said",
  "diciendo": "saying",
  "diciéndole": "telling him",
  "dieciocho": "eighteen",
  "dificultosamente": "with difficulty",
  "digo": "I say",
  "dijo": "he said",
  "diminutos": "tiny",
  "dinamita": "dynamite",
  "dio": "gave",
  "dios": "God",
  "dirección": "direction",
  "dirigieron": "they directed",
  "divorciarse": "to divorce",
  "dobló": "bent",
  "don": "gift",
  "dormida": "asleep",
  "dormitaba": "dozing",
  "dormitorio": "bedroom",
  "dos": "two",
  "dote": "dowry",
  "duda": "doubt",
  "durante": "during",
  "duro": "hard",
  "duros": "hard",
  "e": "e",
  "echaba": "was throwing",
  "echándole": "throwing it at him",
  "echar": "to throw",
  "echó": "threw",
  "eco": "echo",
  "efectivamente": "indeed",
  "el": "the",
  "él": "he",
  "elevaba": "was raising",
  "ella": "she",
  "ellos": "they",
  "embargo": "however",
  "en": "in",
  "enamoraron": "fell in love",
  "encajes": "lace",
  "encaminó": "set on a path",
  "encantado": "enchanted",
  "encendida": "lit",
  "encendidas": "lit",
  "encerrarla": "lock her up",
  "encima": "on top",
  "encogió": "shrank",
  "enfermedad": "illness",
  "enormes": "enormous",
  "enseguida": "right away",
  "entabló": "struck up",
  "entender": "understand",
  "entonces": "then",
  "entraba": "was entering",
  "entre": "between",
  "entretelas": "interlining",
  "entró": "entered",
  "envenenarse": "poison oneself",
  "envoltura": "wrapping",
};
