export const spanishGlosses750: Readonly<Record<string, string>> = {
  "sangre": "blood",
  "santa": "holy",
  "santiago": "Santiago",
  "santiagués": "from Santiago",
  "se": "is",
  "sé": "I know",
  "seguía": "continued",
  "semblante": "countenance",
  "sensación": "sensation",
  "sensibilizado": "sensitive",
  "sentía": "felt",
  "señor": "sir",
  "ser": "to be",
  "serenó": "calmed",
  "sería": "would be",
  "serio": "serious",
  "serles": "to be for them",
  "setecientos": "seven hundred",
  "severidad": "severity",
  "si": "if",
  "sí": "yes",
  "siempre": "always",
  "sienes": "temples",
  "sigilosamente": "stealthily",
  "siglo": "century",
  "siguiente": "next",
  "siguieron": "followed",
  "silencio": "silence",
  "silencioso": "silent",
  "sin": "without",
  "síncope": "syncope",
  "sino": "but",
  "sintió": "felt",
  "siquiera": "even",
  "sirvienta": "maid",
  "sobre": "on",
  "sobrino": "nephew",
  "sola": "alone",
  "solicitó": "requested",
  "sollozos": "sobs",
  "solo": "alone",
  "solterón": "bachelor",
  "sonrió": "smiled",
  "sonrisitas": "little smiles",
  "soñadas": "dreamed",
  "soy": "I am",
  "su": "his",
  "subdelirio": "subdelirium",
  "subía": "was rising",
  "subido": "risen",
  "sublevaban": "were stirring up",
  "succión": "suction",
  "sudor": "sweat",
  "suegro": "father-in-law",
  "suelo": "floor",
  "sueños": "dreams",
  "suma": "sum",
  "superiores": "superiors",
  "supuesto": "supposed",
  "sus": "his",
  "suyas": "hers",
  "tajo": "slash",
  "tal": "such",
  "también": "also",
  "tamborileó": "drummed",
  "tan": "so",
  "tarde": "late",
  "temblando": "trembling",
  "temblar": "to tremble",
  "tener": "to have",
  "tenía": "had",
  "tentativa": "attempt",
  "tercer": "third",
  "ternero": "calf",
  "ternura": "tenderness",
  "terrores": "terrors",
  "testarudo": "stubborn",
  "tiene": "has",
  "tímida": "shy",
  "tío": "uncle",
  "tiraba": "pulled",
  "tirar": "to pull",
  "tísica": "consumptive",
  "tocaran": "played",
  "toda": "all",
  "todavía": "still",
  "todo": "everything",
  "todos": "everyone",
  "tomar": "to take",
  "tomó": "took",
  "torpedos": "torpedoes",
  "trapicheos": "scheming",
  "treinta": "thirty",
  "trepaban": "were climbing",
  "tres": "three",
  "trinó": "chirped",
  "trompa": "trunk",
  "tropezado": "stumbled",
  "tuvo": "had",
  "última": "last",
  "ultimátum": "ultimatum",
  "último": "last",
  "un": "one",
  "una": "one",
  "única": "only",
  "únicamente": "only",
  "uno": "one",
  "ustedes": "you all",
  "vaciado": "emptied",
  "vaivén": "back-and-forth",
  "valdría": "would be worth",
  "valiera": "were worth",
  "valorizada": "valued",
  "van": "go",
  "varease": "be fanned",
  "varón": "male",
  "veces": "times",
  "veían": "saw",
  "veinte": "twenty",
  "velludas": "hairy",
  "velo": "veil",
  "vendía": "sold",
  "verdad": "truth",
  "verdadera": "true",
  "verlo": "to see it",
  "vertiginosa": "dizzying",
  "vez": "time",
  "vía": "way",
  "vida": "life",
  "viejas": "old",
  "villa": "villa",
  "viscosa": "viscous",
  "visiblemente": "visibly",
  "vistas": "sights",
  "vivía": "lived",
  "vivían": "lived",
  "viviente": "living",
  "vivieron": "lived",
  "volaron": "flew",
  "volviendo": "returning",
  "volvieron": "returned",
  "volvió": "returned",
  "vómitos": "vomiting",
  "voz": "voice",
  "y": "and",
  "ya": "already",
  "yacía": "lay",
  "yo": "I",
};
