export const spanishGlosses600: Readonly<Record<string, string>> = {
  "ojos": "eyes",
  "olas": "waves",
  "olvidan": "forget",
  "onza": "ounce",
  "ordenándole": "ordering him",
  "orgullo": "pride",
  "oscuras": "dark",
  "oso": "bear",
  "otoñal": "autumnal",
  "otoño": "autumn",
  "otra": "another",
  "otro": "another",
  "ovillo": "ball of yarn",
  "padre": "father",
  "pagar": "pay",
  "palabra": "word",
  "palacio": "palace",
  "palma": "palm",
  "par": "pair",
  "para": "for",
  "parásitos": "parasites",
  "parece": "it seems",
  "parecen": "they seem",
  "parecía": "it seemed",
  "paredes": "walls",
  "pareja": "couple",
  "parra": "vine",
  "parte": "part",
  "particularmente": "particularly",
  "pasábanse": "they were passing by",
  "pasando": "passing",
  "pasándose": "passing by",
  "paseábase": "he was strolling",
  "pasó": "he passed",
  "pasos": "steps",
  "pataleta": "tantrum",
  "patas": "paws",
  "patio": "courtyard",
  "pelado": "bald",
  "pelo": "hair",
  "pena": "sorrow",
  "pensar": "to think",
  "peor": "worse",
  "perdía": "was losing",
  "perdió": "lost",
  "perfiles": "profiles",
  "perlaron": "sparkled",
  "pero": "but",
  "persignarse": "cross oneself",
  "pesa": "weighs",
  "pesaba": "weighed",
  "pesar": "to weigh",
  "petición": "request",
  "picadura": "bite",
  "picaduras": "bites",
  "pidió": "asked",
  "piedras": "stones",
  "pieza": "piece",
  "plata": "silver",
  "plato": "plate",
  "pleno": "full",
  "pluma": "pen",
  "plumas": "pens",
  "pobretón": "poor fellow",
  "pobreza": "poverty",
  "poco": "little",
  "poder": "power",
  "podía": "could",
  "ponderar": "weigh",
  "por": "by",
  "porfiadas": "stubborn",
  "porque": "because",
  "postulante": "candidate",
  "precio": "price",
  "preciso": "precise",
  "presente": "present",
  "primeras": "first",
  "principio": "beginning",
  "probable": "probable",
  "procesión": "procession",
  "producía": "produced",
  "profundamente": "deeply",
  "pronto": "soon",
  "pronunciaba": "pronounced",
  "proporciones": "proportions",
  "proseguía": "continued",
  "pudo": "could",
  "puerta": "door",
  "pues": "well",
  "puesta": "set",
  "puesto": "post",
  "pulsaban": "they pressed",
  "puso": "he set",
  "que": "that",
  "qué": "what",
  "quedado": "remaining",
  "quedó": "remained",
  "querer": "to want",
  "quería": "he wanted",
  "quien": "who",
  "quién": "who",
  "quieren": "they want",
  "quiso": "he wanted",
  "rabia": "rage",
  "raimundo": "Raimundo",
  "raíz": "root",
  "rancio": "stale",
  "rápidamente": "quickly",
  "raro": "strange",
  "ras": "scratch",
  "rasguño": "scratch",
  "rata": "rat",
  "rato": "moment",
  "ratos": "moments",
  "real": "real",
  "recién": "just",
  "redoblando": "redoubling",
  "reemplazar": "replace",
  "regalaría": "would give",
  "regalarle": "give him",
  "regalase": "give",
  "remitía": "forwarded",
  "remoción": "removal",
  "renunció": "resigned",
  "repente": "suddenly",
  "reponía": "restored",
  "resonancia": "resonance",
  "resopló": "snorted",
  "respaldo": "backing",
  "retardándose": "slowing down",
  "rey": "king",
  "rígida": "rigid",
  "rígido": "rigid",
  "rogaba": "begged",
  "rompió": "broke",
  "ronca": "hoarse",
  "rosa": "pink",
  "rubia": "blonde",
  "ruido": "noise",
  "rumor": "rumor",
  "saber": "to know",
  "saberlo": "to know it",
  "sacar": "to take out",
  "sacerdote": "priest",
  "sala": "room",
  "salía": "was leaving",
  "salieron": "they left",
  "salir": "to leave",
  "salvadora": "saving",
  "san": "healthy",
};
