export const spanishGlosses450: Readonly<Record<string, string>> = {
  "juró": "swore",
  "kilos": "kilograms",
  "la": "the",
  "labios": "lips",
  "lado": "side",
  "lados": "sides",
  "largamente": "at length",
  "largo": "long",
  "las": "the",
  "le": "him",
  "lectores": "readers",
  "leer": "to read",
  "lenguas": "languages",
  "lentamente": "slowly",
  "levantada": "raised",
  "levántelo": "raise it",
  "levantó": "raised",
  "leve": "slight",
  "ligera": "light",
  "ligero": "lightweight",
  "lima": "file",
  "limeñitas": "little people from Lima",
  "limeños": "people from Lima",
  "limpio": "clean",
  "linajudo": "well-bred",
  "linda": "pretty",
  "litigio": "litigation",
  "lívida": "livid",
  "llamaba": "called",
  "llamado": "called",
  "llámeme": "call me",
  "llamó": "called",
  "llanto": "cry",
  "llegaba": "arrived",
  "llegan": "arrive",
  "llegara": "would arrive",
  "llegó": "arrived",
  "llenó": "filled",
  "llevándose": "taking",
  "lloró": "cried",
  "lo": "it",
  "loco": "crazy",
  "logro": "achievement",
  "los": "the",
  "luces": "lights",
  "lucía": "shone",
  "luego": "then",
  "luis": "Luis",
  "luna": "moon",
  "luz": "light",
  "madre": "mother",
  "madrid": "Madrid",
  "madroño": "strawberry tree",
  "mancebo": "young man",
  "manchas": "spots",
  "manchitas": "little spots",
  "mano": "hand",
  "manos": "hands",
  "mañana": "tomorrow",
  "maravedí": "maravedí",
  "marcha": "march",
  "margarita": "daisy",
  "marido": "husband",
  "mármol": "marble",
  "más": "more",
  "matar": "to kill",
  "me": "me",
  "media": "half",
  "medicina": "medicine",
  "médico": "doctor",
  "médicos": "doctors",
  "medio": "half",
  "mejor": "better",
  "mejorase": "to get better",
  "menor": "younger",
  "menos": "less",
  "merecida": "deserved",
  "mesa": "table",
  "meses": "months",
  "meterse": "to get involved",
  "miel": "honey",
  "mientras": "while",
  "mil": "thousand",
  "millón": "million",
  "mimada": "spoiled",
  "miraba": "was looking",
  "mirada": "look",
  "mirando": "looking",
  "mirándolo": "looking at him",
  "mirar": "to look",
  "mirarlo": "to look at him",
  "miró": "looked",
  "mis": "my",
  "mismo": "same",
  "momento": "moment",
  "monedas": "coins",
  "monja": "nun",
  "monótono": "monotonous",
  "monstruos": "monsters",
  "monstruoso": "monstrous",
  "mover": "to move",
  "moverse": "to move",
  "moviendo": "moving",
  "muchacha": "girl",
  "mucho": "a lot",
  "muchos": "many",
  "mudo": "silent",
  "muebles": "furniture",
  "muerte": "death",
  "mujer": "woman",
  "muñeca": "doll",
  "muñecas": "dolls",
  "murió": "died",
  "murmuró": "murmured",
  "muy": "very",
  "nacía": "was born",
  "nada": "nothing",
  "narices": "noses",
  "negativa": "negative",
  "negó": "denied",
  "negra": "black",
  "negros": "blacks",
  "nervios": "nerves",
  "nerviosa": "nervous",
  "ni": "nor",
  "nido": "nest",
  "niña": "girl",
  "niñerías": "childishness",
  "no": "no",
  "noche": "night",
  "noches": "nights",
  "novia": "girlfriend",
  "nuestro": "our",
  "nuevas": "news",
  "nuevo": "new",
  "nunca": "never",
  "nupcial": "bridal",
  "o": "or",
  "obsequiarle": "to give her a gift",
  "observación": "observation",
  "observaron": "they observed",
  "obstáculo": "obstacle",
  "obstante": "however",
  "obstinación": "stubbornness",
  "ocasión": "occasion",
  "ochavo": "eighth",
  "oía": "he heard",
  "oído": "ear",
  "oír": "to hear",
  "ojo": "eye",
};
