export const spanishCanonicalGlosses: Readonly<Record<string, string>> = {
  "acabó": "finished",
  "acomoda": "arrange",
  "acontecía": "was happening",
  "acuse": "accuse",
  "ad": "ad",
  "adónde": "where",
  "alfiler": "pin",
  "ante": "before",
  "aquél": "that one",
  "arguyó": "argued",
  "arrodillándose": "kneeling",
  "autor": "author",
  "bastón": "cane",
  "bien": "well",
  "canto": "song",
  "capa": "cape",
  "case": "married",
  "chica": "girl",
  "cierto": "certain",
  "coger": "to take",
  "colectorcillo": "little collector",
  "concédame": "grant me",
  "condene": "condemn",
  "conmigo": "with me",
  "consagrada": "consecrated",
  "consienta": "consent",
  "consiento": "I consent",
  "cristianos": "Christians",
  "cuestión": "question",
  "darían": "would give",
  "darte": "to give you",
  "das": "you give",
  "debe": "must",
  "dejará": "will leave",
  "dejarlo": "to leave it",
  "desabrimiento": "disappointment",
  "desahuciado": "evicted",
  "desairar": "to snub",
  "diez": "ten",
  "divina": "divine",
  "emparentar": "to be related",
  "encapillado": "stacked",
  "entiende": "understand",
  "esta": "this",
  "gallardo": "dashing",
  "ha": "has",
  "habrase": "would have",
  "insolencia": "insolence",
  "ir": "go",
  "juro": "I swear",
  "laya": "kind",
  "libro": "book",
  "litterae": "litterae",
  "llevar": "carry",
  "mala": "bad",
  "matemos": "let’s kill",
  "mi": "my",
  "misa": "Mass",
  "muchacho": "boy",
  "muera": "die",
  "necesita": "needs",
  "nos": "us",
  "notable": "notable",
  "obsequiarla": "give it as a gift",
  "obstinado": "stubborn",
  "ocho": "eight",
  "olvidándose": "forgetting",
  "pactado": "agreed",
  "paraguay": "Paraguay",
  "paso": "step",
  "pecho": "chest",
  "pedem": "pedem",
  "perjurare": "perjury",
  "posta": "post",
  "puede": "can",
  "razonable": "reasonable",
  "regalará": "will give as a gift",
  "regale": "give as a gift",
  "renunciamos": "we renounce",
  "retirarse": "withdraw",
  "satisfecho": "satisfied",
  "sea": "be",
  "según": "according to",
  "te": "you",
  "terciando": "intervening",
  "tú": "you",
  "usted": "you",
  "va": "go",
  "varee": "vary",
  "vendrá": "will come",
  "vengo": "I come",
  "vista": "sight",
  "visto": "seen",
};
